### ISSUE TITLE
Docker Ready

### ISSUE THREAD

**Issue by GianlucaScarciolla** [PROGRADE-Tech/Tarchivebot#17]
I think it would be great if `Tarchivebot` would run in a **Docker container**.
The idea is that a user simply can install `Tarchivebot` on his server.

Opinions?

**Comment by fuerbringer** [comment]
This ofcourse is a great idea, though I wouldn't recommend going for docker compatibility in the [MVP](https://github.com/PROGRADE-Tech/Tarchivebot/milestone/1).

I had this in the back of my head, which is why I've already created the dockerfiles. They just need to be  set up correct. Again, I do not plan on implementing them until after MVP. In other words: Docker compatibility isn't yet core functionality, which is what the MVP is shooting for.

Just my thoughts 👍

**Comment by GianlucaScarciolla** [comment]
@fuerbringer I agree! For the first release/MVP is it to early. Was thinking about a later Alpha release.

**Comment by fuerbringer** [comment]
_Sigh_. We're always prioritizing "doable" stuff before things that are actually important for the next release (MVP in this case).

Anyways this has been implemented in #41.
