### ISSUE TITLE
Data seems to not be loaded on first open of panel

### ISSUE THREAD

**Issue by Hoi15A** [PROGRADE-Tech/Tarchivebot#44]
I assume this is likely due to the key not being sent when you add a key for the first time. However I am not sure and need to look into this bug more.

This should be reproducible by clearing local storage and reloading the page

**Comment by fuerbringer** [comment]
This only seems to happen when the application is run behind a reverse proxy (NGINX). Because I don't think it's due to it being dockerized.

Scrot: ![tarchive api calls](https://a.lainfile.pw/1YWSUbXgVq)

**Comment by fuerbringer** [comment]
This issue appears to be fixed with the following commits:
- https://github.com/PROGRADE-Tech/Tarchivebot/commit/87d16c071a2e161b7c53802424626aeb52d3b12f
- https://github.com/PROGRADE-Tech/Tarchivebot/commit/59df19e2881cd728a06d61fd9bd719868781a6c5
- https://github.com/PROGRADE-Tech/Tarchivebot/commit/c1ab721b3a05bae5e19a8049670900d088ff938d
- https://github.com/PROGRADE-Tech/Tarchivebot/commit/8f67129d599e67f60046de200984bde237a777e6
- https://github.com/PROGRADE-Tech/Tarchivebot/commit/7fea59e79f49b3c698da22b5928d84d1b8e0ab2f

**Please reopen this issue if the bug still persists.**
